[package]
name = "maze"
version = "0.1.0"
edition = "2021"

[dependencies]
const-random = "0.1.18"
rand = "0.8.5"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
ndarray = "0.15.6"
tract-onnx = "0.19.3"
anyhow = "1.0"
image = "0.24.6"
num_cpus = "1.16.0"
